import setupLogInPage from "./logIn.js";
import setupContactsPage from "./contacts.js";
import setupAboutPage from "./about.js";
import setupPressPage from "./press.js";
import setupBrokerPage from "./broker.js";
import setupMainPage from "./mainPage.js";


function router() {
  switch (window.location.hash) {
    case "":
      //document.querySelector("main").innerHTML = mainPage();
      //document.querySelector("main").innerHTML = "";
      //setupMainPage();
      //break;
      // Clear the main section
      document.querySelector("main").innerHTML = "";

      // Append the content generated by setupMainPage
      document.querySelector("main").appendChild(setupMainPage());
      break;

    case "#broker":
      document.querySelector("main").innerHTML = "";
      document.querySelector("main").appendChild(setupBrokerPage());
      //setupBrokerPage();
      break;

    case "#logIn":
      //document.querySelector("main").innerHTML = logIn();
      //setupLogInPage();
      document.querySelector("main").innerHTML = "";

      // Append the content generated by setupMainPage
      //document.querySelector("main").appendChild(setupLogInPage());
      //setupLogInPage();
      document.querySelector('main').appendChild(setupLogInPage());
      break;

    case "#contacts":
      document.querySelector("main").innerHTML = "";
      //document.querySelector("main").appendChild(setupContactsPage());
      setupContactsPage();
      break;

    case "#about":
      document.querySelector("main").innerHTML = "";
      //document.querySelector("main").innerHTML = about();
      document.querySelector('main').appendChild(setupAboutPage());
      break;

    case "#press":
      //document.querySelector("main").innerHTML = press();
      //break;
      document.querySelector("main").innerHTML = "";
      setupPressPage();
      //document.querySelector("main").innerHTML = "";
      break;


    default:
      document.querySelector("main").innerHTML = "<h1>Sidan finns inte</h1>";
  }
}

document.addEventListener('DOMContentLoaded', router);
window.addEventListener('hashchange', router);

